Lesson3
innamitryaevacps/Basic-Python-Inna pull request #5
Opened 2020-07-21 22:07 UTC by innamitryaevacps

2020-07-25 05:30 UTC, sergeychaikacps requested changes

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +print("YES" if k%n == 0 or k%m == 0 else "NO")
Почему при размерах 1х6 нельзя поделить на 5 частей?

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +    print(penguine[i]*n)
Давай сделаем с помощью tabulate

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +    summa *= num
Давай сделаем через for

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +    summa += x*x
** 2 работает быстрее и понятнее

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +print(-b/a)
Давай ограничим количество знаком после запятой в выводе

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +    if b == 0:
Давай будем проверять с заданной погрешностью

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +phrase = "На лугу пасется {} коров".format(n)
Давай сделаем через шаблон или через f-строки (https://python-scripts.com/string-formatting)

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +    print(phrase + "ы")
Условия лучше реализовать через остаток от деления

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +        print(x)
Давай попробуем векторизировать вычисления (https://zyatev.ru/analiz-dannykh/python-vektorizatsiia-tsiklov-s-usloviiami-daet-uskorenie-primerno-na-20-50) и замерить время выполнения разных способов вычисления

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +        print(x)
И давай ещё с помощью scipy реализуем (https://habr.com/ru/post/419453) и замерим

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +    if str(x) == str(x**2)[-3:]:
Не надо сравнивать строки! Используй остаток от деления

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +    if str(x) == str(x**2)[-3:]:
И давай эту задачу то же векторизируем и замерим

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +    print(nums[:i])
Давай сделаем ещё одну реализацию - через вложенный цикл
И замерим обе

2020-07-25 05:30 UTC, sergeychaikacps commented on Lesson3.py
> +print(res)
Давай замерим время исполнения

2020-07-25 12:30 UTC, merged

2020-07-25 14:43 UTC, innamitryaevacps commented on Lesson3.py
> +print("YES" if k%n == 0 or k%m == 0 else "NO")
Можно. Он "yes" выдает

2020-07-26 05:18 UTC, sergeychaikacps commented on Lesson3.py
> +print("YES" if k%n == 0 or k%m == 0 else "NO")
Согласен

2020-07-26 05:20 UTC, sergeychaikacps commented on Lesson3.py
> +print("YES" if k%n == 0 or k%m == 0 else "NO")
А разве можно от шоколадки 2х6 отломить подшоколадку в 18 долек?

2020-07-28 15:06 UTC, sergeychaikacps commented on Lesson3.py
> +b = int(input())
Почему int?