Lesson4
innamitryaevacps/Basic-Python-Inna pull request #8
Opened 2020-07-23 13:01 UTC by innamitryaevacps

2020-07-25 06:42 UTC, sergeychaikacps requested changes

2020-07-25 06:42 UTC, sergeychaikacps commented on Lessson4.py
> +print(s[:s.find("h")] + s[s.rfind("h")+1:] if s[-1] != "h" else s[:s.find("h")])
Можно было покороче
`s[:s.find('h')] + s[s.rfind('h'):][1:]`

2020-07-25 06:42 UTC, sergeychaikacps commented on Lessson4.py
> +l = [x for x in input().split(" ")]
В этих случаях удобно пользоваться np.arange(n).tolist()

2020-07-25 06:42 UTC, sergeychaikacps commented on Lessson4.py
> +last = s.rfind("h")
Это зачем?

2020-07-25 06:42 UTC, sergeychaikacps commented on Lessson4.py
> +print("".join(i + "*" for i in s)[:-1])
Лучше list comprehensions (aka генератор списка) использовать с обозначением списка, то есть вот так:
`''.join([sub_s + '*' for sub_s in s])[:-1]`

2020-07-25 06:42 UTC, sergeychaikacps commented on Lessson4.py
> +l[l.index(max(l))], l[l.index(min(l))] = l[l.index(min(l))], l[l.index(max(l))]
Давай сделаем через np.argmax и np.argmin

2020-07-25 06:42 UTC, sergeychaikacps commented on Lessson4.py
> +l[l.index(max(l))], l[l.index(min(l))] = l[l.index(min(l))], l[l.index(max(l))]
И не будем их искать по два раза

2020-07-25 06:42 UTC, sergeychaikacps commented on Lessson4.py
> +print(len(s))
А можно в одну строчку)

2020-07-25 06:42 UTC, sergeychaikacps commented on Lessson4.py
> +words = input_file.readlines()[0].strip().split(" ")
Зачем [0]?

2020-07-25 06:42 UTC, sergeychaikacps commented on Lessson4.py
> +# Не особо поняла из условия, что тут хотят. Возвращаю кол-во цветов, которые есть в обоих наборах.
Типичная ситуация с типичным клиентом. Клиент что-то хочет, что-то уже сделал по-своему и ТЗ он конечно же составил (как он считает и думает что это кому-то поможет)

В данной задаче:
есть два набора объектов
объектам дали имена
надо вывести статистику по объектам и списки объектов по категориям:

- сколько и какие объекты (то есть по именам) есть в обоих наборах
- сколько и какие объекты (то есть по именам) есть в первом наборе
- сколько и какие объекты (то есть по именам) есть во втором наборе
- сколько и какие объекты (то есть по именам) есть в каком-нибудь наборе (aka уникальные объекты)

2020-07-25 06:42 UTC, sergeychaikacps commented on Lessson4.py
> +        everybody = everybody.union(langs)
Зачем тут объединение?

2020-07-27 13:17 UTC, innamitryaevacps commented on Lessson4.py
> +print(s[:s.find("h")] + s[s.rfind("h")+1:] if s[-1] != "h" else s[:s.find("h")])
хм, не понимаю, что поменялось, но оно начало работать и в таком виде сейчас:
print(s[:s.find("h")] + s[s.rfind("h")+1:])

2020-07-27 14:37 UTC, innamitryaevacps commented on Lessson4.py
> +words = input_file.readlines()[0].strip().split(" ")
без него AttributeError возникает

2020-07-27 14:58 UTC, innamitryaevacps commented on Lessson4.py
> +        everybody = everybody.union(langs)
а как еще?

2020-07-28 05:07 UTC, sergeychaikacps commented
Обнови py файл - не могу проводить ревью

2020-07-28 05:27 UTC, sergeychaikacps requested changes

2020-07-28 05:27 UTC, sergeychaikacps commented on Lessson4.py
> +        everybody = everybody.union(langs)
`if i == 0:
     everybody = copy.deepcopy(langs)`

2020-07-28 05:27 UTC, sergeychaikacps commented on Lessson4.py
> +words = input_file.readlines()[0].strip().split(" ")
Но ты же тогда обработаешь только первую строку. Зачем делать код, который работает только с однострочными файлами?

2020-07-28 05:27 UTC, sergeychaikacps commented on Lessson4.py
> +words = input_file.readlines()[0].strip().split(" ")
Зачем тебе strip в этой задаче?

2020-07-28 05:27 UTC, sergeychaikacps commented on Lessson4.py
> +words = input_file.readlines()[0].strip().split(" ")
Ты понимаешь, почему у тебя AttributeError? Что возвращает readlines?

2020-07-28 05:27 UTC, sergeychaikacps commented on Lessson4.py
> +print(s[:s.find("h")] + s[s.rfind("h")+1:] if s[-1] != "h" else s[:s.find("h")])
Ну, обязательно надо понять

2020-08-01 11:23 UTC, sergeychaikacps requested changes

2020-08-01 11:23 UTC, sergeychaikacps commented on Lessson4.py
> +ls = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Давай заменим на list comprehension

2020-08-01 11:23 UTC, sergeychaikacps commented on Lessson4.py
> +print(b + " " + a)
Давай сделаем через join

2020-08-02 14:00 UTC, innamitryaevacps commented on Lessson4.py
> +words = input_file.readlines()[0].strip().split(" ")
ага, разобралась с этим
для моего файла работало, т.к. в нем всего одна строка, но переделала для общего случая

2020-08-02 14:01 UTC, innamitryaevacps commented on Lessson4.py
> +print(b + " " + a)
а почему так лучше? интересно просто

2020-08-08 04:23 UTC, sergeychaikacps approved these changes
В данном случае апрувлю, но:

1. один недочёт остаётся за тобой
2. юнит тесты на mccme могут выявить ошибки в решениях, а значит надо будет переделывать

В дальнейшем без юнит тестов дальше идти не будем

2020-08-08 04:23 UTC, sergeychaikacps commented on Lessson4.py
> +        unique_words = set(words)
Крайне не желательно использовать тот факт, что в питоне пустые объекты - это False и наоборот

2020-08-08 04:23 UTC, sergeychaikacps commented on Lessson4.py
> +print(" ".join((b, a)))
Так лучше потому что таким образом:

1. разделитель указывается в одном месте, что уменьшает ошибки
2. потенциально, быстрее, так как, как правило, функции быстрее операторов
3. код становится более читаемым

2020-08-08 04:24 UTC, merged